### ISSUE TITLE
Feature Order Cycle detection

### ISSUE THREAD

**Issue by catter1** [jacobsjo/worldgen-devtools#10]
[Cyanide](<https://modrinth.com/mod/cyanide>) has not been updated since 1.20.1. In most of the 1.20.x versions, the 1.20.1 version used to work, but now it officially does not work as of 1.21.x. Supposedly AlcatrazEscappe is aware, but either doesn't have time or does not want to update it; due to how many changes Mojang has made in the past year.

Updating/merging Cyanide completely into Worldgen Devtools is probably a huge ask, so I won't do that. But Cyanide's FOC detection is super useful, and something I use personally all the time. If possible, it would love to see it updated and part of Worldgen Devtools.

**Comment by catter1** [comment]
Good point, if Spyglass adds it, that would probably be better. However, there is still a usecase that Spyglass wouldn't be able to help. Occasionally there are FOCs between serveral mods - Spyglass wouldn't be able to help, and the only soution would be a mod (or the mod just makes it a lot easier)

**Comment by jacobsjo** [comment]
good point. I'd be open to accept a PR for this.

**Comment by jacobsjo** [comment]
Cyanide has been updated, so this isn't needed anymore
