### ISSUE TITLE
Port to 1.20.4

### ISSUE THREAD

**Issue by AnCarsenat** [jacobsjo/worldgen-devtools#9]

**Comment by jacobsjo** [comment]
There is an old alpha build for 1.20.4 that is quite unstable, see https://github.com/jacobsjo/worldgen-devtools/releases/tag/v1.0.0-alpha.5%2B1.20.4

I don't plan to support 1.20.4 anymore

**Comment by AnCarsenat** [comment]
What do you mean Unstable ?

**Comment by jacobsjo** [comment]
Well its an alpha build. It is more likely to crash during reloading.
